#! /usr/bin/python
# Copyright 2016 EMC Corporation

from emc_vmax_smis.vmax_smis_commands import list_sgs

if __name__ == '__main__':
    try:
        list_sgs()
    except KeyboardInterrupt:
        pass
