#! /usr/bin/python
# Copyright 2016 EMC Corporation

from emc_vmax_smis.vmax_smis_commands import mod_sg

if __name__ == '__main__':
    try:
        mod_sg()
    except KeyboardInterrupt:
        pass
