#! /usr/bin/python
# Copyright 2016 EMC Corporation

from emc_vmax_smis.vmax_smis_commands import show_devs

if __name__ == '__main__':
    try:
        show_devs()
    except KeyboardInterrupt:
        pass
