#! /usr/bin/python
# Copyright 2016 EMC Corporation

from emc_vmax_smis.vmax_smis_commands import del_devs

if __name__ == '__main__':
    try:
        del_devs()
    except KeyboardInterrupt:
        pass
