#! /usr/bin/python
# Copyright 2016 EMC Corporation

from emc_vmax_smis.vmax_smis_commands import add_mv

if __name__ == '__main__':
    try:
        add_mv()
    except KeyboardInterrupt:
        pass
