#! /usr/bin/python
# Copyright 2016 EMC Corporation

import os
import sys
import platform
import getopt
from uuid import uuid4
from bitmath import GiB
from emc_vmax_smis.vmax_smis_devices import VmaxSmisDevices

PROGNAME = os.path.basename(sys.argv[0])
USAGE = ('Usage: {0} '
         '-h <host>|--host <host> '
         '-s <symm_id>|--sid <symm_id> '
         '[-u <username>|--user <username>] '
         '[-p <password>|--password <password>]\n\t'
         '[-S|--use_ssl] [-n <name>|--name=<name>]'
         '[-g <sizeGB>|--size=<sizeGB>] [-c <count>|--count=<count>]'
         '-P <pool>|--pool=<pool>\n'.format(PROGNAME))


def usage():
    sys.stderr.write(USAGE)
    return 2


def main():
    try:
        options, remainder = getopt.getopt(sys.argv[1:], 'h:s:u:p:Sn:P:g:c:',
                                           ['host=', 'sid=', 'user=', 'password=', 'use_ssl',
                                            'name=', 'pool=', 'size=', 'count='])
    except getopt.GetoptError as err:
        sys.stderr.write('{0!s}\n'.format(err))
        sys.exit(usage())

    host = os.getenv('SMIS_HOST', None)
    sid = os.getenv('SMIS_SID', None)
    user = os.getenv('SMIS_USER', 'admin')
    password = os.getenv('SMIS_PASSWORD', '#1Password')
    use_ssl = eval(os.getenv('SMIS_SSL', 'False'))
    port = 5989 if use_ssl else 5988
    name = platform.node().split('.')[0]
    pool = None
    size = 1
    count = 1
    for opt, arg in options:
        if opt in ('-h', '--host'):
            host = arg
        elif opt in ('-s', '--sid'):
            sid = arg
        elif opt in ('-u', '--user'):
            user = arg
        elif opt in ('-p', '--password'):
            password = arg
        elif opt in ('-S', '--use_ssl'):
            use_ssl = True
            port = 5989
        elif opt in ('-n', '--name'):
            name = arg
        elif opt in ('-P', '--pool'):
            pool = arg
        elif opt in ('-g', '--size'):
            size = int(arg)
        elif opt in ('-c', '--count'):
            count = int(arg)
        else:
            sys.exit(usage())

    if host is None or sid is None or pool is None:
        sys.exit(usage())

    smis_devices = VmaxSmisDevices(host=host, port=port, user=user, passwd=password, use_ssl=use_ssl)

    for system_name in smis_devices.smis_base.list_storage_system_names():
        if system_name.endswith(sid):
            break
    else:
        raise ReferenceError('%s: symmetrix id not found' % sid)

    storage_pools = smis_devices.list_storage_pools(system_name)
    for storage_pool in storage_pools:
        pool_inst = smis_devices.get_pool_instance(system_name, storage_pool)
        if pool == pool_inst['ElementName']:
            break
    else:
        raise ReferenceError('%s: pool not found or not specified' % pool)

    volume_name = name + '-' + str(uuid4())
    device_ids = smis_devices.create_volumes(system_name, volume_name, storage_pool,
                                             int(GiB(size).to_Byte().value), count=count)
    print str(device_ids)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
