#! /usr/bin/python
# Copyright 2016 EMC Corporation

import os
import sys
import getopt
from emc_vmax_smis.vmax_smis_devices import VmaxSmisDevices

PROGNAME = os.path.basename(sys.argv[0])
USAGE = ('Usage: {0} '
         '-h <host>|--host <host> '
         '-s <symm_id>|--sid <symm_id> '
         '[-u <username>|--user <username>] '
         '[-p <password>|--password <password>] '
         '[-m or -U|--mapped or --unmapped]'
         '[-n <name>|--name=<name>] [-S|--use_ssl]\n'.format(PROGNAME))


def usage():
    sys.stderr.write(USAGE)
    return 2


def main():
    try:
        options, remainder = getopt.getopt(sys.argv[1:], 'h:s:u:p:n:mUS',
                                           ['host=', 'sid=', 'user=', 'password=', 'name=',
                                            'mapped', 'unmapped', 'use_ssl'])
    except getopt.GetoptError as err:
        sys.stderr.write('{0!s}\n'.format(err))
        sys.exit(usage())

    host = os.getenv('SMIS_HOST', None)
    sid = os.getenv('SMIS_SID', None)
    user = os.getenv('SMIS_USER', 'admin')
    password = os.getenv('SMIS_PASSWORD', '#1Password')
    name = None
    mapped_only = False
    unmapped_only = False
    use_ssl = False
    port = 5988
    for opt, arg in options:
        if opt in ('-h', '--host'):
            host = arg
        elif opt in ('-s', '--sid'):
            sid = arg
        elif opt in ('-u', '--user'):
            user = arg
        elif opt in ('-p', '--password'):
            password = arg
        elif opt in ('-n', '--name'):
            name = arg
        elif opt in ('-m', '--mapped') and unmapped_only is False:
            mapped_only = True
        elif opt in ('-U', '--unmapped') and mapped_only is False:
            unmapped_only = True
        elif opt in ('-S', '--use_ssl'):
            use_ssl = True
            port = 5989
        else:
            sys.exit(usage())

    if host is None or sid is None:
        sys.exit(usage())

    smis_devices = VmaxSmisDevices(host=host, port=port, user=user, passwd=password, use_ssl=use_ssl)

    for system_name in smis_devices.smis_base.list_storage_system_names():
        if system_name.endswith(sid):
            break
    else:
        raise ReferenceError('%s: symmetrix id not found' % sid)

    for dev_id in smis_devices.list_all_devices(system_name):
        volume = smis_devices.get_volume_instance(system_name, dev_id)
        if (name is None or volume['ElementName'].startswith(name)) \
                and (mapped_only is False or volume['EMCIsMapped'] is True) \
                and (unmapped_only is False or volume['EMCIsMapped'] is False):
            print str(dev_id) + '\tName=' + volume['ElementName'] + \
                  '\tIsMapped=' + str(volume['EMCIsMapped']) + \
                  '\tIsComposite=' + str(volume['IsComposite'])

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
