#! /usr/bin/python
# Copyright 2016 EMC Corporation

import os
import sys
import getopt
from emc_vmax_smis.vmax_smis_sync import VmaxSmisSync

PROGNAME = os.path.basename(sys.argv[0])
USAGE = ('Usage: {0} '
         '-h <host>|--host <host> '
         '-s <symm_id>|--sid <symm_id> '
         '[-u <username>|--user <username>] '
         '[-p <password>|--password <password>] '
         '[-S|--use_ssl]\n'.format(PROGNAME))


def usage():
    sys.stderr.write(USAGE)
    sys.exit(2)


def main():
    try:
        options, remainder = getopt.getopt(sys.argv[1:], 'h:s:u:p:S',
                                           ['host=', 'sid=', 'user=', 'password=', 'use_ssl'])
    except getopt.GetoptError as err:
        sys.stderr.write('{0!s}\n'.format(err))
        usage()

    host = os.getenv('SMIS_HOST', None)
    sid = os.getenv('SMIS_SID', None)
    user = os.getenv('SMIS_USER', 'admin')
    password = os.getenv('SMIS_PASSWORD', '#1Password')
    use_ssl = False
    port = 5988
    for opt, arg in options:
        if opt in ('-h', '--host'):
            host = arg
        elif opt in ('-s', '--sid'):
            sid = arg
        elif opt in ('-u', '--user'):
            user = arg
        elif opt in ('-p', '--password'):
            password = arg
        elif opt in ('-S', '--use_ssl'):
            use_ssl = True
            port = 5989
        else:
            usage()

    if host is None or sid is None:
        usage()

    smis_sync = VmaxSmisSync(host=host, port=port, user=user, passwd=password, use_ssl=use_ssl)

    for system_name in smis_sync.smis_base.list_storage_system_names():
        if system_name.endswith(sid):
            break
    else:
        raise ReferenceError('%s: symmetrix id not found' % sid)

    for dev_id in remainder:
        while len(dev_id) < 5:
            dev_id = '0' + dev_id
        dev_id = dev_id.upper()
        print dev_id + ':'
        try:
            sync_svs = smis_sync.get_sync_sv_by_device(system_name, dev_id)
            for sync_sv in sync_svs:
                sync_props = smis_sync.get_sync_sv_properties(sync_sv)
                print '\t' + str(smis_sync.get_sync_source(sync_sv)) + ':'
                for prop in sorted(sync_props.keys()):
                    print '\t\t' + str(prop) + ' = ' + str(sync_props[prop])
        except ReferenceError:
            print '\tVolume not found.'

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
